### ISSUE TITLE
Ambiguous use of `parameter` in Xcode 14.3 RC

### ISSUE THREAD

**Issue by IanHoar** [mjarvis/Exhibition#71]
<img width="1323" alt="Screenshot 2023-03-21 at 1 19 23 PM" src="https://user-images.githubusercontent.com/967712/226731187-1a4c2e47-de12-4925-9689-54bb3c01ba22.png">

**Comment by mjarvis** [comment]
you'll need to provide a type for `leftAlignedSelectedIndex` for this to work. `context.parameter` is meant to be provided directly inline on parameters for the view, which provides the necessary type data.

Here, the function doesn't know if you want `Int`, or `Binding<Int>`

So a fix would be `let foo: Int = context.parameter(name: "foo", defaultValue: 0)`, or to not assign to a variable and instead use inline when initializing the view.

**Comment by IanHoar** [comment]
Gotcha! Thanks for that
